# This workflow generates the changelog file in the
# documentation based on the merged pull requests
# See more at: https://github.com/heinrichreimer/action-github-changelog-generator

name: Changelog Generator

on:
  push:
    branches: [ master ]

jobs:
  generate_changelog_file:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate changelog
      uses: browniebroke/action-github-changelog-generator@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        author: true
        unreleased: true
        issues: false
        pullRequests: true
        prWoLabels: false
        compareLink: true
        excludeLabels: automation,dependencies,nochangelog
        breakingLabel: '### ğŸ’¥ Breaking Changes:'
        deprecatedLabel: '### âš ï¸ Deprecations:'
        enhancementLabel: '### ğŸš€ Enhancements:'
        bugsLabel: '### ğŸ› Bug Fixes:'
        removedLabel: '### ğŸ”¥ Removals:'
        addSections: '{"documentation":{"prefix":"### ğŸ“– Documentation updates:","labels":["documentation"]},"tests":{"prefix":"### âœ… Testing:","labels":["tests"]}}'

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update Changelog
        file_pattern: CHANGELOG.md
