# This workflow generates the changelog file in the
# documentation based on the merged pull requests
# See more at: https://github.com/heinrichreimer/action-github-changelog-generator

name: Changelog Generator

on:
  release:
    types:
      - created

jobs:
  generate_changelog_file:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate changelog
      uses: browniebroke/action-github-changelog-generator@patch-2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        author: true
        unreleased: true
        issues: false
        pullRequests: true
        prWoLabels: false
        compareLink: true
        excludeLabels: tests,automation,nochangelog
        output: docs/changelog.md
        breakingLabel: '### âš ï¸ Breaking Changes:'
        deprecatedLabel: '### ğŸš¨ Deprecated:'
        enhancementLabel: '### ğŸš€ Enhancements:'
        bugsLabel: '### ğŸ› Bug Fixes:'
        removedLabel: '### ğŸ—‘ Removals:'
        addSections: '{"documentation":{"prefix":"### ğŸ“– Documentation updates:","labels":["documentation"]}}'

    - name: Commit changes
      run: |
        if [ -n "$(git status --short)" ]
        then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update Changelog" -a
        else
          echo "No changes to commit - skipping"
        fi
    - name: Push
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
